model_list:
  - model_name: nvidia/nemotron-3-ultra-550b-a55b
    litellm_params:
      model: openai/nvidia/nemotron-3-ultra-550b-a55b
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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